# Generated by Django 3.1.6 on 2021-02-02 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modified', models.DateField(default=datetime.date.today)),
                ('separator', models.CharField(max_length=2)),
                ('character', models.CharField(max_length=2)),
            ],
        ),
    ]
