# Generated by Django 3.1.6 on 2021-02-02 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ColumnSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_value', models.IntegerField(null=True)),
                ('to_value', models.IntegerField(null=True)),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schema')),
                ('type_field_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.typefield')),
            ],
        ),
    ]
