# Generated by Django 3.1.6 on 2021-02-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_columnschema_typefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnschema',
            name='name_column',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
