# Generated by Django 3.1.6 on 2021-02-03 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_columnschema_name_column'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Separator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='schema',
            name='character',
        ),
        migrations.RemoveField(
            model_name='schema',
            name='separator',
        ),
        migrations.AddField(
            model_name='schema',
            name='character_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schema',
            name='separator_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.separator'),
            preserve_default=False,
        ),
    ]
