# Generated by Django 3.1.6 on 2021-02-03 22:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210203_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManageSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('status', models.BooleanField()),
                ('path_file', models.CharField(max_length=250)),
                ('rows', models.IntegerField()),
                ('schema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.schema')),
            ],
        ),
    ]
