# Generated by Django 3.1.6 on 2021-02-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_manageschema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manageschema',
            name='path_file',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
