# Generated by Django 3.1.6 on 2021-02-05 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210205_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnschema',
            name='date_create',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
