# Generated by Django 3.1.6 on 2021-02-05 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_columnschema_date_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columnschema',
            name='date_create',
        ),
    ]
